services:
  mysql:
    image: mysql:8.4
    container_name: mysql-spring
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fusex_db
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      #- "3306:3306"
      - target: 3306
        host_ip: 127.0.0.1
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
