services:
  mysql:
    image: mysql:8.4
    container_name: mysql-spring
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fusex_db
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: